(() => {
  "use strict";

  const DEFAULT_NAMES = ["Team 1", "Team 2", "Team 3"];
  const DEFAULT_COLORS = ["#1f77b4", "#d62728", "#2ca02c"];
  const $ = (id) => document.getElementById(id);
  const dom = {
    canvas: $("gameCanvas"), minimap: $("minimapCanvas"), phase: $("phaseLabel"), clock: $("clockLabel"), connection: $("connectionBadge"), sound: $("soundButton"), event: $("eventBanner"),
    lobby: $("lobbyOverlay"), serverUrl: $("serverUrlInput"), pcLabel: $("pcLabelInput"), team: $("teamSelect"), roomInput: $("roomCodeInput"), register: $("registerButton"), registrationForm: $("registrationForm"), lobbyStatus: $("lobbyStatus"),
    studentInputs: [$("student1Input"), $("student2Input"), $("student3Input")], healthDot: $("serverHealthDot"), healthTitle: $("serverHealthTitle"), healthText: $("serverHealthText"),
    waitingPanel: $("waitingPanel"), waitingStage: $("waitingStageLabel"), waitingMessage: $("waitingMessage"), waitingRoom: $("waitingRoomCode"), waitingPc: $("waitingPcLabel"), waitingTeam: $("waitingTeam"), waitingStudents: $("waitingStudents"),
    approvedPanel: $("approvedPanel"), roomCodeLarge: $("roomCodeLarge"), readyButton: $("readyButton"), assignedColor: $("assignedTeamColor"), assignedName: $("assignedTeamName"), namingStatus: $("teamNamingStatus"), teamCapacity: $("teamCapacity"), roster: $("rosterList"),
    proposalPanel: $("proposalPanel"), proposalProgress: $("proposalProgress"), proposalLabels: [$("proposal1Label"), $("proposal2Label"), $("proposal3Label")], proposalInputs: [$("proposal1Input"), $("proposal2Input"), $("proposal3Input")], submitProposals: $("submitProposalsButton"),
    votePanel: $("votePanel"), voteProgress: $("voteProgress"), voteLabels: [$("vote1Label"), $("vote2Label"), $("vote3Label")], voteSelects: [$("vote1Select"), $("vote2Select"), $("vote3Select")], candidateBoard: $("candidateBoard"), submitVotes: $("submitVotesButton"),
    roomCodeLabel: $("roomCodeLabel"), playerTeamDot: $("playerTeamDot"), playerName: $("playerNameLabel"), playerState: $("playerStateLabel"), playerMembers: $("playerMembersLabel"), playerReady: $("playerReadyLabel"), playerTerritory: $("playerTerritoryLabel"), playerKills: $("playerKillsLabel"), playerDeaths: $("playerDeathsLabel"), playerAccuracy: $("playerAccuracyLabel"), shotCooldown: $("shotCooldown"), dashCooldown: $("dashCooldown"),
    teamCards: [$("team0Card"), $("team1Card"), $("team2Card")], teamNames: [$("team0Name"), $("team1Name"), $("team2Name")], teamTerritory: [$("team0Territory"), $("team1Territory"), $("team2Territory")], teamKills: [$("team0Kills"), $("team1Kills"), $("team2Kills")],
    questionOverlay: $("questionOverlay"), questionTitle: $("questionTitle"), questionTimer: $("questionTimer"), questionCanvas: $("questionCanvas"), questionPrompt: $("questionPrompt"), questionOptions: $("questionOptions"), questionFeedback: $("questionFeedback"),
    endOverlay: $("endOverlay"), winnerSummary: $("winnerSummary"), finalRanking: $("finalRanking"), reportBody: $("reportTableBody"), downloadCsv: $("downloadCsvButton"), downloadJson: $("downloadJsonButton"), returnLobby: $("returnLobbyButton")
  };

  const ctx = dom.canvas.getContext("2d");
  const miniCtx = dom.minimap.getContext("2d");
  const questionCtx = dom.questionCanvas.getContext("2d");
  const state = {
    ws: null, serverUrl: "", roomCode: "", role: "none", registrationId: "", playerId: "", sessionToken: "", pcLabel: "", students: ["", "", ""], team: 0, ready: false,
    phase: "lobby", arena: { width: 1600, height: 1000, gridWidth: 40, gridHeight: 25 }, teamNames: [...DEFAULT_NAMES], teamColors: [...DEFAULT_COLORS], players: [], projectiles: [], territory: [], territoryCounts: [0, 0, 0], remainingMs: 300000,
    serverNowOffset: 0, currentQuestion: null, report: null, reconnectTimer: null, reconnectAttempt: 0, manuallyClosed: false, soundEnabled: true, audioContext: null, bannerTimer: null,
    input: { up: false, down: false, left: false, right: false, shoot: false, dash: false, angle: 0 }
  };

  function initialServerUrl() { const query = new URLSearchParams(location.search).get("server"); return query || localStorage.getItem("triadServerUrl") || window.TRIAD_CONFIG?.serverUrl || ""; }
  function normalizeServerUrl(raw) { let value = String(raw || "").trim().replace(/\/$/, ""); if (!value) throw new Error("The multiplayer server URL is missing."); if (value.startsWith("https://")) value = `wss://${value.slice(8)}`; if (value.startsWith("http://")) value = `ws://${value.slice(7)}`; if (!/^wss?:\/\//i.test(value)) throw new Error("The server URL must begin with wss:// or https://."); return value; }
  function readSession() { try { return JSON.parse(localStorage.getItem("triadStudentSession") || "null"); } catch { return null; } }
  function saveSession() { localStorage.setItem("triadStudentSession", JSON.stringify({ serverUrl: state.serverUrl, roomCode: state.roomCode, sessionToken: state.sessionToken, role: state.role })); }
  function clearSession() { localStorage.removeItem("triadStudentSession"); state.roomCode = ""; state.registrationId = ""; state.playerId = ""; state.sessionToken = ""; state.role = "none"; }
  function setConnection(mode, text) { dom.connection.className = `connection-badge ${mode}`; dom.connection.textContent = text; }
  function setLobbyStatus(text, kind = "neutral") { dom.lobbyStatus.textContent = text; dom.lobbyStatus.style.borderLeftColor = kind === "error" ? "#b42318" : kind === "success" ? "#067647" : "#344054"; }
  function showHealth(mode, title, text) { dom.healthDot.className = `health-dot ${mode}`; dom.healthTitle.textContent = title; dom.healthText.textContent = text; }
  function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char])); }
  function rgba(hex, alpha) { const clean = String(hex || "#000000").replace("#", ""); const value = parseInt(clean.length === 3 ? clean.split("").map((c) => c + c).join("") : clean, 16); return `rgba(${(value >> 16) & 255},${(value >> 8) & 255},${value & 255},${alpha})`; }
  function updateTeamMeta(names = state.teamNames, colors = state.teamColors) { state.teamNames = names?.length === 3 ? names : state.teamNames; state.teamColors = colors?.length === 3 ? colors : state.teamColors; for (let team = 0; team < 3; team += 1) { dom.teamNames[team].textContent = state.teamNames[team].toUpperCase(); dom.teamCards[team].style.setProperty("--team-color", state.teamColors[team]); } dom.playerTeamDot.style.background = state.teamColors[state.team]; }

  dom.serverUrl.value = initialServerUrl();
  dom.pcLabel.value = localStorage.getItem("triadPcLabel") || "";
  dom.team.value = localStorage.getItem("triadTeam") || "0";
  const savedStudents = (() => { try { return JSON.parse(localStorage.getItem("triadStudents") || "[]"); } catch { return []; } })();
  dom.studentInputs.forEach((input, index) => { input.value = savedStudents[index] || ""; });
  const queryRoom = new URLSearchParams(location.search).get("room");
  const stored = readSession();
  dom.roomInput.value = (queryRoom || stored?.roomCode || "").toUpperCase();
  updateTeamMeta();

  function connect() {
    const url = normalizeServerUrl(dom.serverUrl.value); state.serverUrl = url; localStorage.setItem("triadServerUrl", url);
    if (state.ws?.readyState === WebSocket.OPEN && state.ws.url === url) return Promise.resolve(state.ws);
    if (state.ws) { state.manuallyClosed = true; state.ws.close(); state.manuallyClosed = false; }
    setConnection("connecting", "CONNECTING");
    return new Promise((resolve, reject) => {
      const ws = new WebSocket(url); state.ws = ws;
      const timeout = setTimeout(() => { if (ws.readyState !== WebSocket.OPEN) ws.close(); reject(new Error("The Render server did not respond. Open its HTTPS URL once to wake it, then retry.")); }, 18000);
      ws.addEventListener("open", () => { clearTimeout(timeout); state.reconnectAttempt = 0; setConnection("online", "ONLINE"); showHealth("online", "Game server online", "Secure WebSocket connection established."); resolve(ws); }, { once: true });
      ws.addEventListener("error", () => { clearTimeout(timeout); reject(new Error("Unable to connect to the multiplayer server.")); }, { once: true });
      ws.addEventListener("message", onMessage); ws.addEventListener("close", onClose);
    });
  }
  function send(payload) { if (state.ws?.readyState === WebSocket.OPEN) state.ws.send(JSON.stringify(payload)); }
  async function probeServer() { try { const url = normalizeServerUrl(dom.serverUrl.value); showHealth("", "Checking game server…", "Render free services may need up to a minute to wake."); await new Promise((resolve, reject) => { const ws = new WebSocket(url); const timer = setTimeout(() => { try { ws.close(); } catch {} reject(new Error("timeout")); }, 16000); ws.addEventListener("message", (event) => { try { const message = JSON.parse(event.data); if (message.type === "hello" && Number(message.protocol) >= 3) { clearTimeout(timer); ws.close(); resolve(); } } catch {} }); ws.addEventListener("error", () => { clearTimeout(timer); reject(new Error("connection")); }); }); showHealth("online", "Protocol 3 server online", "Three-student registration, voting and simple bots are available."); } catch { showHealth("offline", "Server sleeping or outdated", "Open the Render HTTPS URL, confirm protocol 3, then reload this page."); } }

  async function registerStudent() {
    try {
      const code = dom.roomInput.value.trim().toUpperCase(); const pcLabel = dom.pcLabel.value.trim(); const students = dom.studentInputs.map((input) => input.value.trim());
      if (!/^[A-Z2-9]{6}$/.test(code)) throw new Error("Enter the six-character room code provided by the teacher.");
      if (pcLabel.length < 2) throw new Error("Enter the PC/group label.");
      if (students.some((name) => name.length < 2)) throw new Error("Register all three student names.");
      if (new Set(students.map((name) => name.toLowerCase())).size !== 3) throw new Error("The three student names must be different.");
      localStorage.setItem("triadPcLabel", pcLabel); localStorage.setItem("triadStudents", JSON.stringify(students)); localStorage.setItem("triadTeam", dom.team.value); clearSession();
      state.pcLabel = pcLabel; state.students = students; await connect(); send({ type: "register_student", roomCode: code, pcLabel, students, preferredTeam: Number(dom.team.value) });
      dom.register.disabled = true; setLobbyStatus("Three-student registration sent to the teacher controller.", "success");
    } catch (error) { setConnection("offline", "OFFLINE"); setLobbyStatus(error.message, "error"); dom.register.disabled = false; }
  }

  function onMessage(event) {
    let message; try { message = JSON.parse(event.data); } catch { return; }
    switch (message.type) {
      case "hello": state.serverNowOffset = message.serverTime - Date.now(); break;
      case "registration_received":
        state.role = "pending"; state.roomCode = message.roomCode; state.registrationId = message.registrationId; state.sessionToken = message.sessionToken; state.pcLabel = message.pcLabel; state.students = message.students; saveSession();
        dom.registrationForm.classList.add("hidden"); dom.waitingPanel.classList.remove("hidden"); dom.approvedPanel.classList.add("hidden"); dom.waitingRoom.textContent = state.roomCode; dom.waitingPc.textContent = state.pcLabel; dom.waitingStudents.textContent = state.students.join(" · "); dom.waitingTeam.textContent = `Team slot ${message.preferredTeam + 1} preference`; dom.waitingStage.textContent = "REGISTRATION RECEIVED"; dom.waitingMessage.textContent = "Waiting for teacher approval and final team assignment…"; dom.playerName.textContent = state.pcLabel; dom.playerMembers.textContent = state.students.join(" · "); dom.playerState.textContent = "Pending teacher approval"; dom.roomCodeLabel.textContent = state.roomCode; setLobbyStatus("Connected to the real room. Keep this page open.", "success"); beep(520, 0.08); break;
      case "joined":
        state.role = "player"; state.roomCode = message.roomCode; state.playerId = message.playerId; state.sessionToken = message.sessionToken; state.pcLabel = message.pcLabel; state.students = message.students; state.team = message.team; state.ready = Boolean(message.ready); state.arena = message.arena || state.arena; saveSession();
        dom.registrationForm.classList.add("hidden"); dom.waitingPanel.classList.add("hidden"); dom.approvedPanel.classList.remove("hidden"); dom.roomCodeLarge.textContent = state.roomCode; dom.roomCodeLabel.textContent = state.roomCode; dom.playerName.textContent = state.pcLabel; dom.playerMembers.textContent = state.students.join(" · "); updateTeamMeta(); setLobbyStatus(message.reconnected ? "Approved PC-group session restored." : "Teacher approved this PC group. Complete suggestions and voting.", "success"); beep(720, 0.1); break;
      case "team_assigned": state.team = message.team; updateTeamMeta(); showEvent(`Teacher assigned team slot ${state.team + 1}.`); break;
      case "proposals_accepted": setLobbyStatus("All three suggestions were accepted.", "success"); dom.submitProposals.disabled = true; break;
      case "votes_accepted": setLobbyStatus("All three votes were accepted.", "success"); dom.submitVotes.disabled = true; break;
      case "lobby": state.phase = message.phase; renderLobby(message); break;
      case "countdown": state.phase = "countdown"; dom.lobby.classList.remove("visible"); showEvent(`Match starts in ${message.seconds}…`); beep(660, 0.12); break;
      case "state": applyServerState(message); break;
      case "question": showQuestion(message); break;
      case "answer_result": handleAnswerResult(message); break;
      case "respawned": state.currentQuestion = null; dom.questionOverlay.classList.remove("visible"); dom.questionFeedback.textContent = ""; showEvent("Correct. Respawn authorized by the server."); beep(760, 0.12); break;
      case "event": showEvent(message.text); break;
      case "match_ended": state.phase = "ended"; state.report = message.report; renderFinalReport(message.winners, message.report); break;
      case "removed": clearSession(); state.manuallyClosed = true; state.ws?.close(); alert(message.message || "This PC group was removed from the room."); location.reload(); break;
      case "error": setLobbyStatus(message.message || "Server request failed.", "error"); dom.register.disabled = false; dom.submitProposals.disabled = false; dom.submitVotes.disabled = false; showEvent(message.message); beep(180, 0.14); break;
      case "pong": state.serverNowOffset = message.serverTime - Date.now(); break;
      default: break;
    }
  }
  function onClose() { setConnection("offline", "OFFLINE"); state.ws = null; if (state.manuallyClosed) return; const session = readSession(); if (!session?.sessionToken || state.phase === "ended") { setLobbyStatus("Disconnected from the server.", "error"); return; } scheduleReconnect(session); }
  function scheduleReconnect(session) { clearTimeout(state.reconnectTimer); const delay = Math.min(1000 * 2 ** state.reconnectAttempt, 8000); state.reconnectAttempt += 1; setLobbyStatus(`Connection lost. Reconnecting in ${Math.ceil(delay / 1000)} seconds…`); state.reconnectTimer = setTimeout(async () => { try { dom.serverUrl.value = session.serverUrl; await connect(); send({ type: "reconnect_student", roomCode: session.roomCode, sessionToken: session.sessionToken }); } catch { scheduleReconnect(session); } }, delay); }

  function renderLobby(message) {
    state.roomCode = message.roomCode; updateTeamMeta(message.teamNames, message.teamColors);
    if (message.phase === "lobby" && state.role === "player") { dom.endOverlay.classList.remove("visible"); dom.lobby.classList.add("visible"); dom.approvedPanel.classList.remove("hidden"); state.report = null; }
    if (state.role === "pending") { const me = message.pending.find((item) => item.id === state.registrationId); dom.waitingStage.textContent = message.registrationLocked ? "REGISTRATION LOCKED" : "IN APPROVAL QUEUE"; dom.waitingMessage.textContent = me ? `Teacher sees this PC registration. ${message.pending.length} pending request(s).` : "Waiting for approval…"; setLobbyStatus(`${message.players.length}/9 player slots · ${message.realPcCount} real PCs · ${message.botCount} bots · ${message.pending.length} pending.`, "success"); }
    if (state.role !== "player") return;
    const me = message.players.find((player) => player.id === state.playerId); if (!me) return;
    state.team = me.team; state.ready = me.ready; state.pcLabel = me.pcLabel; state.students = me.students; updateTeamMeta(message.teamNames, message.teamColors); updateVoting(message, me);
    dom.teamCapacity.innerHTML = message.teamCounts.map((count, team) => `<div class="capacity-card" style="--team-color:${escapeHtml(state.teamColors[team])}"><span>${escapeHtml(state.teamNames[team])}</span><b>${count}/3</b></div>`).join("");
    dom.roster.innerHTML = [...message.players].sort((a, b) => a.team - b.team || a.pcLabel.localeCompare(b.pcLabel)).map((player) => `<div class="roster-card ${player.connected ? "" : "disconnected"} ${player.ready ? "" : "not-ready"}" style="--team-color:${escapeHtml(state.teamColors[player.team])}"><strong>${escapeHtml(player.pcLabel)}${player.id === state.playerId ? " · THIS PC" : ""}${player.isBot ? '<span class="bot-badge">AI</span>' : ""}</strong><small>${escapeHtml(state.teamNames[player.team])} · ${player.connected ? (player.ready ? "READY" : "NOT READY") : "OFFLINE"}</small><span class="member-line">${escapeHtml(player.students.join(" · "))}</span></div>`).join("");
    dom.playerReady.textContent = state.ready ? "YES" : "NO"; dom.playerName.textContent = state.pcLabel; dom.playerMembers.textContent = state.students.join(" · "); dom.playerState.textContent = state.ready ? "Approved · ready" : "Approved · setup incomplete";
    setLobbyStatus(`${message.realPcCount} real PC group(s) · ${message.botCount} AI bot(s) · ${message.readyCount}/9 ready.`, message.startReady ? "success" : "neutral");
  }

  function updateVoting(message, me) {
    const naming = message.teamNaming[me.team]; dom.assignedColor.style.background = naming.color; dom.assignedName.textContent = naming.finalized ? naming.name : `Team slot ${me.team + 1} · voting in progress`; dom.namingStatus.textContent = `${naming.proposalCount}/9 suggestions · ${naming.voteCount}/9 votes`;
    state.students.forEach((student, index) => { dom.proposalLabels[index].textContent = `${student}'s suggestion`; dom.voteLabels[index].textContent = `${student}'s vote`; });
    dom.proposalProgress.textContent = me.proposalsSubmitted ? "3 / 3 sent" : "0 / 3 sent"; dom.proposalInputs.forEach((input) => { input.disabled = me.proposalsSubmitted; }); dom.submitProposals.disabled = me.proposalsSubmitted;
    dom.voteProgress.textContent = me.votesSubmitted ? "3 / 3 votes" : "0 / 3 votes"; dom.votePanel.classList.toggle("disabled-panel", !naming.votingOpen); dom.candidateBoard.innerHTML = naming.candidates.length ? naming.candidates.map((candidate) => `<div class="candidate-card"><strong>${escapeHtml(candidate.name)}</strong><span>${candidate.votes} vote(s)</span></div>`).join("") : '<div class="empty-state">Waiting for team suggestions.</div>';
    const options = `<option value="">Choose a candidate…</option>${naming.candidates.map((candidate) => `<option value="${escapeHtml(candidate.key)}">${escapeHtml(candidate.name)}</option>`).join("")}`;
    dom.voteSelects.forEach((select) => { if (!me.votesSubmitted) select.innerHTML = options; select.disabled = !naming.votingOpen || me.votesSubmitted; }); dom.submitVotes.disabled = !naming.votingOpen || me.votesSubmitted;
    const canReady = me.proposalsSubmitted && me.votesSubmitted && naming.finalized; dom.readyButton.disabled = !canReady; dom.readyButton.textContent = state.ready ? "READY — CLICK TO CANCEL" : canReady ? "I AM READY" : "COMPLETE VOTING FIRST"; dom.readyButton.classList.toggle("secondary-button", state.ready);
  }

  function submitProposals() { const names = dom.proposalInputs.map((input) => input.value.trim()); if (names.some((name) => name.length < 2)) { setLobbyStatus("Each of the three students must suggest a team name.", "error"); return; } dom.submitProposals.disabled = true; send({ type: "submit_team_proposals", names }); }
  function submitVotes() { const candidateKeys = dom.voteSelects.map((select) => select.value); if (candidateKeys.some((key) => !key)) { setLobbyStatus("Each of the three students must cast a vote.", "error"); return; } dom.submitVotes.disabled = true; send({ type: "submit_team_votes", candidateKeys }); }

  function applyServerState(message) { state.phase = message.phase; state.players = message.players || []; state.projectiles = message.projectiles || []; state.territory = message.territory || []; state.territoryCounts = message.territoryCounts || [0, 0, 0]; state.remainingMs = message.remainingMs; state.serverNowOffset = message.serverNow - Date.now(); state.arena = message.arena || state.arena; updateTeamMeta(message.teamNames, message.teamColors); dom.phase.textContent = String(message.phase || "").toUpperCase(); if (["playing", "countdown"].includes(message.phase)) dom.lobby.classList.remove("visible"); updateHud(); }
  function updateHud() { const total = state.arena.gridWidth * state.arena.gridHeight; for (let team = 0; team < 3; team += 1) { dom.teamTerritory[team].textContent = `${(total ? state.territoryCounts[team] / total * 100 : 0).toFixed(1)}%`; dom.teamKills[team].textContent = state.players.filter((p) => p.team === team).reduce((sum, p) => sum + p.kills, 0); } const me = state.players.find((p) => p.id === state.playerId); if (!me) return; dom.playerName.textContent = me.pcLabel; dom.playerMembers.textContent = me.students.join(" · "); dom.playerState.textContent = !me.connected ? "Disconnected" : me.alive ? (me.invulnerable ? "Alive · shielded" : "Alive") : "Eliminated · solve trigonometry"; dom.playerTerritory.textContent = me.territory; dom.playerKills.textContent = me.kills; dom.playerDeaths.textContent = me.deaths; dom.playerAccuracy.textContent = me.accuracy == null ? "—" : `${Math.round(me.accuracy * 100)}%`; const now = Date.now() + state.serverNowOffset; dom.shotCooldown.value = me.shotReadyAt <= now ? 1 : Math.max(0, 1 - (me.shotReadyAt - now) / 380); dom.dashCooldown.value = me.dashReadyAt <= now ? 1 : Math.max(0, 1 - (me.dashReadyAt - now) / 3200); }

  function showQuestion(message) { state.currentQuestion = message; dom.questionOverlay.classList.add("visible"); dom.questionTitle.textContent = "Solve correctly to respawn"; dom.questionPrompt.textContent = message.prompt; dom.questionFeedback.textContent = ""; dom.questionFeedback.className = "question-feedback"; dom.questionOptions.innerHTML = ""; message.options.forEach((option, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "question-option"; button.textContent = option; button.addEventListener("click", () => submitAnswer(index)); dom.questionOptions.appendChild(button); }); drawQuestionDiagram(message.diagram); beep(300, 0.1); }
  function submitAnswer(selectedIndex) { if (!state.currentQuestion) return; [...dom.questionOptions.children].forEach((button) => { button.disabled = true; }); send({ type: "answer", questionId: state.currentQuestion.id, selectedIndex }); }
  function handleAnswerResult(message) { if (message.correct) { dom.questionFeedback.textContent = "Correct. Server-authorized respawn in progress…"; dom.questionFeedback.className = "question-feedback correct"; } else { dom.questionFeedback.textContent = message.timeout ? "Time expired. A new question is required." : "Incorrect. A new question is loading."; dom.questionFeedback.className = "question-feedback wrong"; beep(170, 0.13); } }
  function drawQuestionDiagram(diagram = {}) { const c = questionCtx, w = dom.questionCanvas.width, h = dom.questionCanvas.height; c.clearRect(0, 0, w, h); c.fillStyle = "#fbfcfe"; c.fillRect(0, 0, w, h); const a = { x: 110, y: 195 }, b = { x: 450, y: 195 }, top = { x: 450, y: 48 }; c.strokeStyle = "#111827"; c.lineWidth = 4; c.beginPath(); c.moveTo(a.x, a.y); c.lineTo(b.x, b.y); c.lineTo(top.x, top.y); c.closePath(); c.stroke(); c.lineWidth = 2; c.strokeRect(b.x - 24, b.y - 24, 24, 24); c.font = "700 18px system-ui"; c.fillStyle = "#111827"; c.textAlign = "center"; if (diagram.adjacent != null) c.fillText(String(diagram.adjacent), (a.x + b.x) / 2, b.y + 32); if (diagram.opposite != null) c.fillText(String(diagram.opposite), b.x + 42, (b.y + top.y) / 2); if (diagram.hypotenuse != null) c.fillText(String(diagram.hypotenuse), (a.x + top.x) / 2 - 20, (a.y + top.y) / 2 - 12); if (diagram.angle) { c.textAlign = "left"; c.fillText(`${diagram.angle}°`, a.x + 48, a.y - 15); } }

  function renderFinalReport(winners, report) { dom.questionOverlay.classList.remove("visible"); dom.endOverlay.classList.add("visible"); updateTeamMeta(report.teamNames, report.teamColors); const names = winners.map((team) => report.teamNames[team]); dom.winnerSummary.textContent = winners.length === 1 ? `${names[0]} wins by controlling the largest territory.` : `Territory tie: ${names.join(" and ")}.`; const total = state.arena.gridWidth * state.arena.gridHeight; dom.finalRanking.innerHTML = [...report.teams].sort((a, b) => b.territory - a.territory).map((team, index) => `<div class="rank-card" style="--team-color:${escapeHtml(team.color)}"><span>#${index + 1} ${escapeHtml(team.name)}</span><strong>${((team.territory / total) * 100).toFixed(1)}%</strong><small>${team.territory} cells</small></div>`).join(""); dom.reportBody.innerHTML = [...report.players].sort((a, b) => a.team - b.team || a.pcLabel.localeCompare(b.pcLabel)).map((player) => `<tr><td>${escapeHtml(player.pcLabel)}</td><td>${escapeHtml(player.students.join(" · "))}</td><td>${escapeHtml(player.teamName)}</td><td>${player.isBot ? "AI" : "REAL"}</td><td>${player.territory}</td><td>${player.deaths}</td><td>${player.attempts}</td><td>${player.correct}</td><td>${player.wrong}</td><td>${player.timeouts}</td><td>${player.accuracy == null ? "—" : `${Math.round(player.accuracy * 100)}%`}</td></tr>`).join(""); beep(880, 0.18); }
  function reportToCsv(report) { const rows = [["room_code", "pc_group", "students", "team", "type", "territory", "kills", "deaths", "attempts", "correct", "wrong", "timeouts", "accuracy", "average_response_ms"]]; report.players.forEach((p) => rows.push([report.roomCode, p.pcLabel, p.students.join(" | "), p.teamName, p.isBot ? "AI" : "REAL", p.territory, p.kills, p.deaths, p.attempts, p.correct, p.wrong, p.timeouts, p.accuracy ?? "", p.averageResponseMs ?? ""])); rows.push([], ["pc_group", "question_type", "prompt", "selected_option", "correct_option", "outcome", "response_ms"]); report.players.forEach((p) => p.answers.forEach((a) => rows.push([p.pcLabel, a.type, a.prompt, a.selectedIndex == null ? "" : a.options[a.selectedIndex], a.options[a.correctIndex], a.outcome, a.responseMs]))); return rows.map((row) => row.map(csvCell).join(",")).join("\n"); }
  function csvCell(value) { const text = String(value ?? ""); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function download(content, filename, mime) { const blob = new Blob([content], { type: mime }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function showEvent(text) { if (!text) return; dom.event.textContent = text; dom.event.classList.add("visible"); clearTimeout(state.bannerTimer); state.bannerTimer = setTimeout(() => dom.event.classList.remove("visible"), 3200); }

  function resizeCanvas() { const dpr = Math.min(devicePixelRatio || 1, 2); dom.canvas.width = Math.floor(innerWidth * dpr); dom.canvas.height = Math.floor(innerHeight * dpr); dom.canvas.style.width = `${innerWidth}px`; dom.canvas.style.height = `${innerHeight}px`; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); }
  function viewTransform(width = innerWidth, height = innerHeight) { const padX = 24, padTop = 132, padBottom = 92, availableW = width - padX * 2, availableH = height - padTop - padBottom, scale = Math.max(0.1, Math.min(availableW / state.arena.width, availableH / state.arena.height)); return { scale, offsetX: (width - state.arena.width * scale) / 2, offsetY: padTop + (availableH - state.arena.height * scale) / 2 }; }
  function worldFromClient(x, y) { const t = viewTransform(); return { x: (x - t.offsetX) / t.scale, y: (y - t.offsetY) / t.scale }; }
  function draw() { const width = innerWidth, height = innerHeight; ctx.clearRect(0, 0, width, height); ctx.fillStyle = "#eef2f7"; ctx.fillRect(0, 0, width, height); const t = viewTransform(width, height); ctx.save(); ctx.translate(t.offsetX, t.offsetY); ctx.scale(t.scale, t.scale); ctx.fillStyle = "#fbfcfe"; ctx.fillRect(0, 0, state.arena.width, state.arena.height); const cw = state.arena.width / state.arena.gridWidth, ch = state.arena.height / state.arena.gridHeight; for (let gy = 0; gy < state.arena.gridHeight; gy += 1) for (let gx = 0; gx < state.arena.gridWidth; gx += 1) { const owner = state.territory[gy * state.arena.gridWidth + gx]; if (owner >= 0) { ctx.fillStyle = rgba(state.teamColors[owner], 0.28); ctx.fillRect(gx * cw, gy * ch, cw + 0.5, ch + 0.5); } } ctx.strokeStyle = "rgba(17,24,39,.08)"; ctx.lineWidth = 1 / t.scale; for (let gx = 0; gx <= state.arena.gridWidth; gx += 1) { ctx.beginPath(); ctx.moveTo(gx * cw, 0); ctx.lineTo(gx * cw, state.arena.height); ctx.stroke(); } for (let gy = 0; gy <= state.arena.gridHeight; gy += 1) { ctx.beginPath(); ctx.moveTo(0, gy * ch); ctx.lineTo(state.arena.width, gy * ch); ctx.stroke(); } for (const projectile of state.projectiles) { ctx.fillStyle = state.teamColors[projectile.team]; ctx.beginPath(); ctx.arc(projectile.x, projectile.y, 6, 0, Math.PI * 2); ctx.fill(); } for (const player of state.players) drawPlayer(ctx, player, t.scale); ctx.strokeStyle = "#98a2b3"; ctx.lineWidth = 3 / t.scale; ctx.strokeRect(0, 0, state.arena.width, state.arena.height); ctx.restore(); drawMinimap(); const seconds = Math.max(0, Math.ceil(state.remainingMs / 1000)); dom.clock.textContent = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; if (state.currentQuestion) dom.questionTimer.textContent = Math.max(0, Math.ceil((state.currentQuestion.expiresAt - (Date.now() + state.serverNowOffset)) / 1000)); requestAnimationFrame(draw); }
  function drawPlayer(target, player, scale) { target.save(); target.translate(player.x, player.y); target.globalAlpha = player.connected ? 1 : 0.35; if (!player.alive) { target.strokeStyle = "#667085"; target.lineWidth = 5 / scale; target.beginPath(); target.moveTo(-14, -14); target.lineTo(14, 14); target.moveTo(14, -14); target.lineTo(-14, 14); target.stroke(); } else { if (player.invulnerable) { target.strokeStyle = "rgba(17,24,39,.45)"; target.lineWidth = 4 / scale; target.beginPath(); target.arc(0, 0, 24, 0, Math.PI * 2); target.stroke(); } target.rotate(player.angle); target.fillStyle = state.teamColors[player.team]; target.beginPath(); target.moveTo(22, 0); target.lineTo(-14, 14); target.lineTo(-10, 0); target.lineTo(-14, -14); target.closePath(); target.fill(); target.strokeStyle = player.id === state.playerId ? "#111827" : "white"; target.lineWidth = player.id === state.playerId ? 5 / scale : 3 / scale; target.stroke(); } target.restore(); target.save(); target.font = `${Math.max(13, 15 / scale)}px system-ui`; target.textAlign = "center"; target.fillStyle = "#111827"; target.fillText(`${player.pcLabel}${player.isBot ? " · AI" : ""}`, player.x, player.y - 27); target.restore(); }
  function drawMinimap() { const w = dom.minimap.width, h = dom.minimap.height; miniCtx.clearRect(0, 0, w, h); miniCtx.fillStyle = "#fff"; miniCtx.fillRect(0, 0, w, h); const sx = w / state.arena.width, sy = h / state.arena.height, cw = state.arena.width / state.arena.gridWidth, ch = state.arena.height / state.arena.gridHeight; for (let gy = 0; gy < state.arena.gridHeight; gy += 1) for (let gx = 0; gx < state.arena.gridWidth; gx += 1) { const owner = state.territory[gy * state.arena.gridWidth + gx]; if (owner >= 0) { miniCtx.fillStyle = rgba(state.teamColors[owner], 0.34); miniCtx.fillRect(gx * cw * sx, gy * ch * sy, cw * sx + 1, ch * sy + 1); } } for (const p of state.players) { miniCtx.fillStyle = p.alive ? state.teamColors[p.team] : "#98a2b3"; miniCtx.beginPath(); miniCtx.arc(p.x * sx, p.y * sy, p.id === state.playerId ? 5 : 3, 0, Math.PI * 2); miniCtx.fill(); } }

  function inputPayload() { let dx = (state.input.right ? 1 : 0) - (state.input.left ? 1 : 0), dy = (state.input.down ? 1 : 0) - (state.input.up ? 1 : 0), magnitude = Math.hypot(dx, dy); if (magnitude > 1) { dx /= magnitude; dy /= magnitude; } return { type: "input", dx, dy, angle: state.input.angle, shoot: state.input.shoot, dash: state.input.dash }; }
  setInterval(() => { if (state.phase === "playing") send(inputPayload()); }, 1000 / 30); setInterval(() => send({ type: "ping", clientTime: Date.now() }), 15000);
  function keyState(event, pressed) { const key = event.key.toLowerCase(); if (["w", "arrowup"].includes(key)) state.input.up = pressed; if (["s", "arrowdown"].includes(key)) state.input.down = pressed; if (["a", "arrowleft"].includes(key)) state.input.left = pressed; if (["d", "arrowright"].includes(key)) state.input.right = pressed; if (key === " ") { state.input.shoot = pressed; event.preventDefault(); } if (key === "shift") state.input.dash = pressed; }
  addEventListener("keydown", (event) => keyState(event, true)); addEventListener("keyup", (event) => keyState(event, false)); addEventListener("blur", () => Object.assign(state.input, { up: false, down: false, left: false, right: false, shoot: false, dash: false })); dom.canvas.addEventListener("mousemove", (event) => { const world = worldFromClient(event.clientX, event.clientY); const me = state.players.find((p) => p.id === state.playerId); if (me) state.input.angle = Math.atan2(world.y - me.y, world.x - me.x); }); dom.canvas.addEventListener("mousedown", () => { state.input.shoot = true; }); addEventListener("mouseup", () => { state.input.shoot = false; });

  dom.register.addEventListener("click", registerStudent); dom.roomInput.addEventListener("input", () => { dom.roomInput.value = dom.roomInput.value.toUpperCase().replace(/[^A-Z2-9]/g, ""); }); dom.submitProposals.addEventListener("click", submitProposals); dom.submitVotes.addEventListener("click", submitVotes);
  dom.readyButton.addEventListener("click", () => { state.ready = !state.ready; send({ type: "set_ready", ready: state.ready }); });
  dom.downloadCsv.addEventListener("click", () => state.report && download(reportToCsv(state.report), `triad-${state.report.roomCode}-report.csv`, "text/csv;charset=utf-8")); dom.downloadJson.addEventListener("click", () => state.report && download(JSON.stringify(state.report, null, 2), `triad-${state.report.roomCode}-report.json`, "application/json")); dom.returnLobby.addEventListener("click", () => { clearSession(); location.href = "index.html"; });
  dom.sound.addEventListener("click", () => { state.soundEnabled = !state.soundEnabled; dom.sound.textContent = state.soundEnabled ? "SOUND ON" : "SOUND OFF"; dom.sound.setAttribute("aria-pressed", String(state.soundEnabled)); }); addEventListener("resize", resizeCanvas);
  function beep(frequency, duration) { if (!state.soundEnabled) return; try { state.audioContext ||= new (window.AudioContext || window.webkitAudioContext)(); const oscillator = state.audioContext.createOscillator(), gain = state.audioContext.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(0.045, state.audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, state.audioContext.currentTime + duration); oscillator.connect(gain).connect(state.audioContext.destination); oscillator.start(); oscillator.stop(state.audioContext.currentTime + duration); } catch {} }

  resizeCanvas(); requestAnimationFrame(draw); setConnection("offline", "OFFLINE"); probeServer();
  if (stored?.sessionToken && stored?.roomCode) { dom.serverUrl.value = stored.serverUrl || dom.serverUrl.value; setTimeout(async () => { try { await connect(); send({ type: "reconnect_student", roomCode: stored.roomCode, sessionToken: stored.sessionToken }); } catch (error) { setLobbyStatus(`Automatic reconnection failed: ${error.message}`, "error"); } }, 500); }
})();
