"use strict";

const crypto = require("node:crypto");
const http = require("node:http");
const express = require("express");
const { WebSocketServer, WebSocket } = require("ws");

const PORT = Number(process.env.PORT || 8080);
const ALLOWED_ORIGINS = String(process.env.ALLOWED_ORIGINS || "*").split(",").map((v) => v.trim()).filter(Boolean);
const PROTOCOL = 3;
const MATCH_DURATION_MS = 5 * 60 * 1000;
const QUESTION_DURATION_MS = 20 * 1000;
const RECONNECT_GRACE_MS = 60 * 1000;
const ROOM_IDLE_TTL_MS = 45 * 60 * 1000;
const TICK_RATE = 20;
const STATE_RATE = 10;
const DT = 1 / TICK_RATE;
const ARENA = Object.freeze({ width: 1600, height: 1000, gridWidth: 40, gridHeight: 25 });
const CELL_W = ARENA.width / ARENA.gridWidth;
const CELL_H = ARENA.height / ARENA.gridHeight;
const MAX_PLAYERS = 9;
const PLAYERS_PER_TEAM = 3;
const STUDENTS_PER_PC = 3;
const MAX_PENDING = 24;
const PLAYER_RADIUS = 16;
const PLAYER_SPEED = 230;
const DASH_SPEED = 610;
const DASH_DURATION_MS = 180;
const DASH_COOLDOWN_MS = 3200;
const SHOT_COOLDOWN_MS = 380;
const PROJECTILE_SPEED = 760;
const PROJECTILE_LIFETIME_MS = 1400;
const DEFAULT_TEAM_NAMES = ["Team 1", "Team 2", "Team 3"];
const COLOR_PALETTE = ["#1f77b4", "#d62728", "#2ca02c", "#9467bd", "#ff7f0e", "#17becf", "#e377c2", "#8c564b", "#bcbd22"];
const SAFE_BOT_NAMES = ["Vector Vanguard", "Angle Alliance", "Triangle Titans", "Cosine Crew", "Sine Squad", "Thales Force", "Pythagoras Pulse", "Geometry Guild", "Ratio Rangers", "Arc Architects", "Vertex Victory", "Proof Patrol"];
const BANNED_WORDS = ["fuck", "shit", "bitch", "cunt", "asshole", "dick", "pussy", "mierda", "puta", "puto", "putas", "putos", "hijueputa", "hpta", "gonorrea", "marica", "maricon", "pendejo", "pendeja", "cabron", "cabrona", "malparido", "malparida"];

const rooms = new Map();
const app = express();
app.disable("x-powered-by");
app.use(express.json({ limit: "16kb" }));
app.get("/", (_req, res) => res.json({ service: "Triad Territory Rush authoritative server", status: "ok", rooms: rooms.size, protocol: PROTOCOL, architecture: "teacher-controller-nine-pc-groups-voting-and-ai" }));
app.get("/health", (_req, res) => res.json({ status: "ok", protocol: PROTOCOL, uptimeSeconds: Math.floor(process.uptime()) }));
app.get("/status", (_req, res) => res.json({ status: "ok", rooms: [...rooms.values()].map((room) => room.publicStatus()) }));
const server = http.createServer(app);
const wss = new WebSocketServer({ noServer: true, maxPayload: 32 * 1024 });
server.on("upgrade", (req, socket, head) => {
  if (!originAllowed(req.headers.origin)) { socket.write("HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n"); socket.destroy(); return; }
  wss.handleUpgrade(req, socket, head, (ws) => wss.emit("connection", ws, req));
});

function originAllowed(origin) { return ALLOWED_ORIGINS.includes("*") || Boolean(origin && ALLOWED_ORIGINS.includes(origin)); }
function id(prefix = "id") { return `${prefix}_${crypto.randomBytes(10).toString("hex")}`; }
function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
function sanitizeText(value, fallback = "", max = 28) { return String(value || fallback).replace(/[<>\r\n\t]/g, " ").replace(/\s+/g, " ").trim().slice(0, max); }
function normalizedLeetspeak(value) { return sanitizeText(value, "", 80).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/0/g, "o").replace(/[1!|]/g, "i").replace(/3/g, "e").replace(/[4@]/g, "a").replace(/[5$]/g, "s").replace(/7/g, "t"); }
function canonicalText(value) { return normalizedLeetspeak(value).replace(/[^a-z]/g, ""); }
function canonicalNameTokens(value) {
  const tokens = normalizedLeetspeak(value).split(/[^a-z]+/g).filter(Boolean);
  const collapsedShortRuns = [];
  let run = "";
  for (const token of tokens) {
    if (token.length <= 2) { run += token; if (run.length > 18) run = token; }
    else { if (run) collapsedShortRuns.push(run); run = ""; }
  }
  if (run) collapsedShortRuns.push(run);
  return [...tokens, ...collapsedShortRuns];
}
function containsBannedLanguage(value) {
  const banned = new Set(BANNED_WORDS.map(canonicalText));
  return canonicalNameTokens(value).some((token) => banned.has(token));
}
function assertSafeName(value, label, min = 2, max = 28) { const clean = sanitizeText(value, "", max); if (clean.length < min) throw new Error(`${label} must contain at least ${min} characters.`); if (containsBannedLanguage(clean)) throw new Error(`${label} contains prohibited language. Choose a respectful name.`); return clean; }
function parseStudentNames(values) { if (!Array.isArray(values) || values.length !== STUDENTS_PER_PC) throw new Error("Register exactly three students on this PC."); const names = values.map((value, index) => assertSafeName(value, `Student ${index + 1} name`, 2, 24)); if (new Set(names.map((name) => name.toLowerCase())).size !== STUDENTS_PER_PC) throw new Error("The three registered student names must be different."); return names; }
function validTeam(value) { const team = Number(value); if (![0, 1, 2].includes(team)) throw new Error("Choose a valid team slot."); return team; }
function safeSend(ws, payload) { if (ws && ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(payload)); }
function closeWithMessage(ws, message) { safeSend(ws, { type: "removed", message }); setTimeout(() => { try { ws?.close(1000, message); } catch {} }, 100); }
function makeRoomCode() { const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; for (let attempt = 0; attempt < 100; attempt += 1) { let code = ""; for (let i = 0; i < 6; i += 1) code += alphabet[crypto.randomInt(alphabet.length)]; if (!rooms.has(code)) return code; } throw new Error("Unable to allocate room code."); }
function shuffled(values) { const copy = [...values]; for (let i = copy.length - 1; i > 0; i -= 1) { const j = crypto.randomInt(i + 1); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }
function randomTeamColors() { return shuffled(COLOR_PALETTE).slice(0, 3); }
function teamSpawn(team, slot = 0) { const bases = [{ x: 180, y: 180 }, { x: ARENA.width - 180, y: 180 }, { x: ARENA.width / 2, y: ARENA.height - 170 }]; const angle = (Math.PI * 2 * slot) / 3 + Math.random() * 0.35; return { x: clamp(bases[team].x + Math.cos(angle) * 70, 50, ARENA.width - 50), y: clamp(bases[team].y + Math.sin(angle) * 70, 50, ARENA.height - 50) }; }
function numericOptions(correct, spread = 5, decimals = 1) { const rounded = Number(correct.toFixed(decimals)); const values = new Set([rounded]); while (values.size < 4) { const direction = crypto.randomInt(2) ? 1 : -1; const delta = (crypto.randomInt(1, 5) * spread) / 4; values.add(Number(Math.max(0.1, correct + direction * delta).toFixed(decimals))); } const options = shuffled([...values]); return { options: options.map(String), answerIndex: options.indexOf(rounded) }; }
function createQuestion() { const type = ["sin", "cos", "tan", "pythagoras"][crypto.randomInt(4)]; let prompt; let diagram; let correct; if (type === "pythagoras") { const [a, b, c] = [[3, 4, 5], [5, 12, 13], [8, 15, 17], [7, 24, 25]][crypto.randomInt(4)]; if (crypto.randomInt(2) === 0) { prompt = `A right triangle has legs ${a} and ${b}. What is its hypotenuse?`; correct = c; diagram = { type, adjacent: a, opposite: b, hypotenuse: "?", angle: null }; } else { prompt = `A right triangle has hypotenuse ${c} and one leg ${a}. What is the other leg?`; correct = b; diagram = { type, adjacent: a, opposite: "?", hypotenuse: c, angle: null }; } } else { const angle = [30, 35, 40, 45, 50, 60][crypto.randomInt(6)]; const radians = angle * Math.PI / 180; if (type === "sin") { const h = [10, 12, 15, 18, 20][crypto.randomInt(5)]; correct = h * Math.sin(radians); prompt = `θ = ${angle}° and the hypotenuse is ${h}. Find the opposite side using sin(θ).`; diagram = { type, angle, adjacent: null, opposite: "?", hypotenuse: h }; } else if (type === "cos") { const h = [10, 12, 15, 18, 20][crypto.randomInt(5)]; correct = h * Math.cos(radians); prompt = `θ = ${angle}° and the hypotenuse is ${h}. Find the adjacent side using cos(θ).`; diagram = { type, angle, adjacent: "?", opposite: null, hypotenuse: h }; } else { const a = [6, 8, 10, 12, 15][crypto.randomInt(5)]; correct = a * Math.tan(radians); prompt = `θ = ${angle}° and the adjacent side is ${a}. Find the opposite side using tan(θ).`; diagram = { type, angle, adjacent: a, opposite: "?", hypotenuse: null }; } } const { options, answerIndex } = numericOptions(correct, Math.max(2, correct * 0.18), 1); const now = Date.now(); return { id: id("q"), type, prompt, options: options.map((value) => `${value} units`), answerIndex, diagram, createdAt: now, expiresAt: now + QUESTION_DURATION_MS }; }
function emptyQuestionStats() { return { attempts: 0, correct: 0, wrong: 0, timeouts: 0, totalResponseMs: 0, history: [] }; }

class Room {
  constructor(code) {
    this.code = code; this.phase = "lobby"; this.registrationLocked = false; this.controller = null;
    this.pending = new Map(); this.players = new Map(); this.projectiles = new Map();
    this.teamColors = randomTeamColors(); this.teamNames = [...DEFAULT_TEAM_NAMES]; this.teamNamesFinalized = [false, false, false];
    this.teamProposals = [[], [], []]; this.teamVotes = [new Map(), new Map(), new Map()];
    this.territory = new Int8Array(ARENA.gridWidth * ARENA.gridHeight).fill(-1);
    this.createdAt = Date.now(); this.updatedAt = Date.now(); this.startedAt = null; this.endsAt = null; this.lastStateAt = 0; this.botSerial = 0;
    this.tickHandle = setInterval(() => this.tick(), 1000 / TICK_RATE);
  }
  publicStatus() { return { roomCode: this.code, phase: this.phase, approved: this.players.size, realPcGroups: [...this.players.values()].filter((p) => !p.isBot).length, bots: [...this.players.values()].filter((p) => p.isBot).length, connected: this.connectedPlayers().length, pending: this.pending.size, controllerConnected: Boolean(this.controller?.connected), registrationLocked: this.registrationLocked }; }
  destroy() { clearInterval(this.tickHandle); rooms.delete(this.code); }
  attachController(ws, reconnectToken = null) { if (this.controller && reconnectToken !== this.controller.token) throw new Error("This room already has a teacher controller. Use RESTORE PREVIOUS CONTROL."); if (!this.controller) this.controller = { token: id("master"), ws, connected: true, disconnectedAt: null }; else Object.assign(this.controller, { ws, connected: true, disconnectedAt: null }); ws.role = "controller"; ws.roomCode = this.code; this.updatedAt = Date.now(); safeSend(ws, { type: "controller_joined", protocol: PROTOCOL, roomCode: this.code, masterToken: this.controller.token, arena: ARENA, matchDurationMs: MATCH_DURATION_MS, reconnected: Boolean(reconnectToken) }); this.sendLobby(); if (this.phase === "ended") this.sendFinalTo(ws); }
  duplicateRegistration(pcLabel, students) { const labels = [...this.pending.values(), ...this.players.values()].map((item) => item.pcLabel.toLowerCase()); if (labels.includes(pcLabel.toLowerCase())) return "That PC/group label is already registered."; const existing = new Set([...this.pending.values(), ...this.players.values()].flatMap((item) => item.students.map((name) => name.toLowerCase()))); const duplicate = students.find((name) => existing.has(name.toLowerCase())); return duplicate ? `${duplicate} is already registered in this room.` : null; }
  registerStudent(ws, message) { if (this.phase !== "lobby") throw new Error("This match has already started."); if (this.registrationLocked) throw new Error("The teacher has locked registration."); if (this.players.size >= MAX_PLAYERS) throw new Error("The room already has nine player slots."); if (this.pending.size >= MAX_PENDING) throw new Error("The registration queue is full."); const pcLabel = assertSafeName(message.pcLabel, "PC/group label", 2, 24); const students = parseStudentNames(message.students); const duplicate = this.duplicateRegistration(pcLabel, students); if (duplicate) throw new Error(duplicate); const registrationId = id("reg"); const token = id("student"); const registration = { id: registrationId, token, ws, pcLabel, students, preferredTeam: validTeam(message.preferredTeam), connected: true, createdAt: Date.now() }; this.pending.set(registrationId, registration); ws.role = "pending"; ws.registrationId = registrationId; ws.roomCode = this.code; this.updatedAt = Date.now(); safeSend(ws, { type: "registration_received", protocol: PROTOCOL, roomCode: this.code, registrationId, sessionToken: token, pcLabel, students, preferredTeam: registration.preferredTeam }); this.sendLobby(); }
  reconnectStudent(ws, token) { const pending = [...this.pending.values()].find((item) => item.token === token); if (pending) { pending.ws = ws; pending.connected = true; ws.role = "pending"; ws.registrationId = pending.id; ws.roomCode = this.code; safeSend(ws, { type: "registration_received", protocol: PROTOCOL, roomCode: this.code, registrationId: pending.id, sessionToken: pending.token, pcLabel: pending.pcLabel, students: pending.students, preferredTeam: pending.preferredTeam, reconnected: true }); this.sendLobby(); return; } const player = [...this.players.values()].find((item) => item.token === token && !item.isBot); if (!player) throw new Error("The previous PC-group session could not be restored."); player.ws = ws; player.connected = true; player.disconnectedAt = null; ws.role = "player"; ws.playerId = player.id; ws.roomCode = this.code; this.sendJoined(player, true); if (player.currentQuestion) this.sendQuestion(player); this.sendLobby(); this.broadcastEvent(`${player.pcLabel} reconnected.`); }
  makePlayer(data, team, isBot = false) { const slot = this.teamCounts(false)[team]; const spawn = teamSpawn(team, slot); return { id: id(isBot ? "bot" : "p"), token: isBot ? null : data.token, ws: isBot ? null : data.ws, pcLabel: data.pcLabel, students: data.students, name: data.pcLabel, team, isBot, connected: true, disconnectedAt: null, ready: isBot, proposalsSubmitted: false, votesSubmitted: false, x: spawn.x, y: spawn.y, angle: 0, alive: true, invulnerableUntil: 0, respawnAt: 0, kills: 0, deaths: 0, nextShotAt: 0, dashUntil: 0, nextDashAt: 0, input: { dx: 0, dy: 0, angle: 0, shoot: false, dash: false }, currentQuestion: null, questionStats: emptyQuestionStats(), ai: isBot ? { nextDecisionAt: 0, nextDashAt: Date.now() + 1500 + crypto.randomInt(2500) } : null };
  }
  approveRegistration(controllerWs, registrationId, teamValue) { this.assertController(controllerWs); if (this.phase !== "lobby") throw new Error("Approval is only available in the lobby."); const registration = this.pending.get(String(registrationId || "")); if (!registration) throw new Error("Registration no longer exists."); const team = validTeam(teamValue); if (this.teamCounts(false)[team] >= PLAYERS_PER_TEAM) throw new Error(`${this.teamNames[team]} already has three player slots.`); if (this.players.size >= MAX_PLAYERS) throw new Error("Nine player slots are already filled."); this.pending.delete(registration.id); const player = this.makePlayer(registration, team, false); this.players.set(player.id, player); if (player.ws) { player.ws.role = "player"; player.ws.playerId = player.id; delete player.ws.registrationId; this.sendJoined(player, false); } this.updatedAt = Date.now(); this.sendLobby(); this.broadcastEvent(`${player.pcLabel} was approved for team slot ${team + 1}.`); }
  rejectRegistration(controllerWs, registrationId) { this.assertController(controllerWs); const registration = this.pending.get(String(registrationId || "")); if (!registration) throw new Error("Registration no longer exists."); this.pending.delete(registration.id); closeWithMessage(registration.ws, "Registration was declined by the teacher."); this.sendLobby(); }
  movePlayer(controllerWs, playerId, teamValue) { this.assertController(controllerWs); if (this.phase !== "lobby") throw new Error("Teams can only be changed before the match."); const player = this.players.get(String(playerId || "")); if (!player) throw new Error("Player slot not found."); if (player.proposalsSubmitted || player.votesSubmitted) throw new Error("This group already began team-name voting. Remove and re-register it to change teams."); const team = validTeam(teamValue); if (team !== player.team && this.teamCounts(false)[team] >= PLAYERS_PER_TEAM) throw new Error("That team already has three player slots."); player.team = team; player.ready = player.isBot; const spawn = teamSpawn(team, Math.max(0, this.teamCounts(false)[team] - 1)); player.x = spawn.x; player.y = spawn.y; safeSend(player.ws, { type: "team_assigned", team }); this.sendLobby(); }
  removePlayer(controllerWs, playerId) { this.assertController(controllerWs); if (this.phase !== "lobby") throw new Error("Players can only be removed in the lobby."); const player = this.players.get(String(playerId || "")); if (!player) throw new Error("Player slot not found."); const team = player.team; this.players.delete(player.id); closeWithMessage(player.ws, "You were removed from the room by the teacher."); this.resetTeamNaming(team); this.sendLobby(); }
  setRegistrationLock(controllerWs, locked) { this.assertController(controllerWs); this.registrationLocked = Boolean(locked); this.sendLobby(); }
  addBots(controllerWs) { this.assertController(controllerWs); if (this.phase !== "lobby") throw new Error("AI bots can only be added in the lobby."); while (this.players.size < MAX_PLAYERS) { const counts = this.teamCounts(false); const min = Math.min(...counts); const team = counts.indexOf(min); this.botSerial += 1; const serial = this.botSerial; const data = { pcLabel: `AI Player ${serial}`, students: [`AI ${serial}-A`, `AI ${serial}-B`, `AI ${serial}-C`] }; const bot = this.makePlayer(data, team, true); this.players.set(bot.id, bot); this.seedBotProposals(bot); } for (const team of [0, 1, 2]) this.autoVoteBots(team); this.sendLobby(); this.broadcastEvent("Missing player slots were filled with simple server bots."); }
  removeBots(controllerWs) { this.assertController(controllerWs); if (this.phase !== "lobby") throw new Error("AI bots can only be removed in the lobby."); for (const [playerId, player] of this.players) if (player.isBot) this.players.delete(playerId); for (const team of [0, 1, 2]) this.resetTeamNaming(team); this.sendLobby(); this.broadcastEvent("All AI bots were removed."); }
  seedBotProposals(bot) { if (bot.proposalsSubmitted) return; const start = (bot.team * 3 + this.botSerial) % SAFE_BOT_NAMES.length; const names = [0, 1, 2].map((offset) => `${SAFE_BOT_NAMES[(start + offset) % SAFE_BOT_NAMES.length]} ${bot.team + 1}`); this.addProposals(bot, names); }
  resetTeamNaming(team) { this.teamProposals[team] = []; this.teamVotes[team] = new Map(); this.teamNames[team] = DEFAULT_TEAM_NAMES[team]; this.teamNamesFinalized[team] = false; for (const player of this.players.values()) if (player.team === team) { player.proposalsSubmitted = false; player.votesSubmitted = false; if (player.isBot) this.seedBotProposals(player); } this.autoVoteBots(team); }
  addProposals(player, values) { if (player.proposalsSubmitted) throw new Error("This PC group already submitted its three suggestions."); if (!Array.isArray(values) || values.length !== 3) throw new Error("Submit exactly three team-name suggestions, one per student."); const names = values.map((value, index) => assertSafeName(value, `Suggestion from ${player.students[index]}`, 2, 28)); const existing = new Set(this.teamProposals[player.team].map((proposal) => canonicalText(proposal.name))); for (const name of names) { const key = canonicalText(name); if (existing.has(key)) throw new Error(`The team name “${name}” was already suggested.`); existing.add(key); } names.forEach((name, index) => this.teamProposals[player.team].push({ key: id("name"), name, playerId: player.id, studentIndex: index, studentName: player.students[index], createdAt: Date.now() + index })); player.proposalsSubmitted = true; }
  submitTeamProposals(playerId, values) { if (this.phase !== "lobby") throw new Error("Team-name suggestions are only available in the lobby."); const player = this.players.get(playerId); if (!player || player.isBot || !player.connected) throw new Error("Real approved PC group required."); this.addProposals(player, values); safeSend(player.ws, { type: "proposals_accepted" }); this.autoVoteBots(player.team); this.sendLobby(); }
  autoVoteBots(team) { const status = this.teamNamingStatus(team); if (!status.votingOpen) return; const candidates = this.teamProposals[team]; const bots = [...this.players.values()].filter((player) => player.team === team && player.isBot); for (const bot of bots) { if (bot.votesSubmitted) continue; const keys = bot.students.map((_student, index) => candidates[(index + bot.id.length) % candidates.length].key); this.addVotes(bot, keys); } this.finalizeTeamName(team); }
  addVotes(player, candidateKeys) { if (player.votesSubmitted) throw new Error("This PC group already submitted its three votes."); const status = this.teamNamingStatus(player.team); if (!status.votingOpen) throw new Error("Voting opens after all nine students on the team submit suggestions."); if (!Array.isArray(candidateKeys) || candidateKeys.length !== 3) throw new Error("Submit exactly three votes, one per student."); const valid = new Set(this.teamProposals[player.team].map((proposal) => proposal.key)); candidateKeys.forEach((candidateKey, index) => { if (!valid.has(String(candidateKey))) throw new Error(`Choose a valid candidate for ${player.students[index]}.`); this.teamVotes[player.team].set(`${player.id}:${index}`, String(candidateKey)); }); player.votesSubmitted = true; }
  submitTeamVotes(playerId, candidateKeys) { if (this.phase !== "lobby") throw new Error("Team-name voting is only available in the lobby."); const player = this.players.get(playerId); if (!player || player.isBot || !player.connected) throw new Error("Real approved PC group required."); this.addVotes(player, candidateKeys); safeSend(player.ws, { type: "votes_accepted" }); this.finalizeTeamName(player.team); this.sendLobby(); }
  finalizeTeamName(team) { const status = this.teamNamingStatus(team); if (!status.votingOpen || status.voteCount < 9) return; const counts = new Map(this.teamProposals[team].map((proposal) => [proposal.key, 0])); for (const candidateKey of this.teamVotes[team].values()) counts.set(candidateKey, (counts.get(candidateKey) || 0) + 1); const ranked = [...this.teamProposals[team]].sort((a, b) => (counts.get(b.key) || 0) - (counts.get(a.key) || 0) || a.createdAt - b.createdAt); this.teamNames[team] = ranked[0]?.name || DEFAULT_TEAM_NAMES[team]; this.teamNamesFinalized[team] = true; this.broadcastEvent(`${this.teamNames[team]} won team ${team + 1}'s vote.`); }
  teamNamingStatus(team) { const proposals = this.teamProposals[team]; const votes = this.teamVotes[team]; const teamFull = this.teamCounts(false)[team] === PLAYERS_PER_TEAM; const votingOpen = teamFull && proposals.length === PLAYERS_PER_TEAM * STUDENTS_PER_PC; const voteCounts = new Map(proposals.map((proposal) => [proposal.key, 0])); for (const key of votes.values()) voteCounts.set(key, (voteCounts.get(key) || 0) + 1); return { team, color: this.teamColors[team], name: this.teamNames[team], finalized: this.teamNamesFinalized[team], proposalCount: proposals.length, proposalTarget: 9, voteCount: votes.size, voteTarget: 9, votingOpen, candidates: proposals.map((proposal) => ({ key: proposal.key, name: proposal.name, studentName: proposal.studentName, votes: voteCounts.get(proposal.key) || 0 })) }; }
  setReady(playerId, ready) { if (this.phase !== "lobby") return; const player = this.players.get(playerId); if (!player || !player.connected || player.isBot) return; const status = this.teamNamingStatus(player.team); if (ready && (!player.proposalsSubmitted || !player.votesSubmitted || !status.finalized)) throw new Error("Complete all three suggestions and votes before marking ready."); player.ready = Boolean(ready); this.sendLobby(); }
  assertController(ws) { if (!this.controller || this.controller.ws !== ws || ws.role !== "controller") throw new Error("Teacher controller authorization required."); }
  sendJoined(player, reconnected) { safeSend(player.ws, { type: "joined", protocol: PROTOCOL, roomCode: this.code, playerId: player.id, sessionToken: player.token, pcLabel: player.pcLabel, students: player.students, team: player.team, ready: player.ready, arena: ARENA, matchDurationMs: MATCH_DURATION_MS, reconnected: Boolean(reconnected) }); }
  teamCounts(connectedOnly = false) { const counts = [0, 0, 0]; for (const player of this.players.values()) if (!connectedOnly || player.isBot || player.connected) counts[player.team] += 1; return counts; }
  connectedPlayers() { return [...this.players.values()].filter((player) => player.isBot || player.connected); }
  readyPlayers() { return [...this.players.values()].filter((player) => player.isBot || (player.connected && player.ready)); }
  startBlockers() { const blockers = []; const counts = this.teamCounts(false); if (this.players.size < MAX_PLAYERS) blockers.push(`${MAX_PLAYERS - this.players.size} player slot(s) missing`); if (!counts.every((count) => count === PLAYERS_PER_TEAM)) blockers.push("teams must be balanced 3–3–3"); const real = [...this.players.values()].filter((p) => !p.isBot); const disconnected = real.filter((p) => !p.connected).length; const notReady = real.filter((p) => !p.ready).length; if (disconnected) blockers.push(`${disconnected} real PC group(s) offline`); if (notReady) blockers.push(`${notReady} real PC group(s) not ready`); if (!this.teamNamesFinalized.every(Boolean)) blockers.push("team-name voting incomplete"); if (!this.controller?.connected) blockers.push("teacher controller offline"); return blockers; }
  lobbySnapshot() { const players = [...this.players.values()].map((player) => ({ id: player.id, pcLabel: player.pcLabel, name: player.pcLabel, students: player.students, team: player.team, connected: player.isBot || player.connected, ready: player.isBot || player.ready, isBot: player.isBot, proposalsSubmitted: player.proposalsSubmitted, votesSubmitted: player.votesSubmitted })); return { type: "lobby", roomCode: this.code, phase: this.phase, capacity: MAX_PLAYERS, studentsPerPc: STUDENTS_PER_PC, registrationLocked: this.registrationLocked, controllerConnected: Boolean(this.controller?.connected), teamCounts: this.teamCounts(false), connectedTeamCounts: this.teamCounts(true), readyCount: this.readyPlayers().length, realPcCount: players.filter((p) => !p.isBot).length, botCount: players.filter((p) => p.isBot).length, teamNames: this.teamNames, teamColors: this.teamColors, teamNaming: [0, 1, 2].map((team) => this.teamNamingStatus(team)), pending: [...this.pending.values()].map((item) => ({ id: item.id, pcLabel: item.pcLabel, students: item.students, preferredTeam: item.preferredTeam, connected: item.connected, createdAt: item.createdAt })), players, startReady: this.startBlockers().length === 0, startBlockers: this.startBlockers() }; }
  allSockets() { const sockets = new Set(); if (this.controller?.ws) sockets.add(this.controller.ws); for (const item of this.pending.values()) if (item.ws) sockets.add(item.ws); for (const player of this.players.values()) if (player.ws) sockets.add(player.ws); return sockets; }
  broadcast(payload) { for (const ws of this.allSockets()) safeSend(ws, payload); }
  sendLobby() { this.broadcast(this.lobbySnapshot()); }
  broadcastEvent(text) { this.broadcast({ type: "event", text, at: Date.now() }); }
  canStart() { return this.startBlockers().length === 0; }
  start(controllerWs) { this.assertController(controllerWs); if (this.phase !== "lobby") throw new Error("The room is not in the lobby."); if (!this.canStart()) throw new Error(`Cannot start: ${this.startBlockers().join("; ")}.`); this.phase = "countdown"; this.registrationLocked = true; this.territory.fill(-1); this.projectiles.clear(); for (const team of [0, 1, 2]) { const members = [...this.players.values()].filter((player) => player.team === team); members.forEach((player, slot) => { const spawn = teamSpawn(team, slot); Object.assign(player, { x: spawn.x, y: spawn.y, angle: 0, alive: true, invulnerableUntil: Date.now() + 2500, respawnAt: 0, kills: 0, deaths: 0, nextShotAt: 0, dashUntil: 0, nextDashAt: 0, currentQuestion: null, questionStats: emptyQuestionStats() }); this.paintTerritory(player.x, player.y, team, 2); }); } this.broadcast({ type: "countdown", seconds: 3 }); this.sendLobby(); setTimeout(() => { if (this.phase !== "countdown") return; this.phase = "playing"; this.startedAt = Date.now(); this.endsAt = this.startedAt + MATCH_DURATION_MS; this.broadcastEvent("Match started. Largest territory after five minutes wins."); }, 3000); }
  endEarly(controllerWs) { this.assertController(controllerWs); if (!["playing", "countdown"].includes(this.phase)) throw new Error("There is no active match to end."); this.endMatch(); }
  reset(controllerWs) { this.assertController(controllerWs); if (this.phase !== "ended") throw new Error("Reset is available after the match ends."); this.phase = "lobby"; this.registrationLocked = false; this.startedAt = null; this.endsAt = null; this.territory.fill(-1); this.projectiles.clear(); const slots = [0, 0, 0]; for (const player of this.players.values()) { const spawn = teamSpawn(player.team, slots[player.team]++); Object.assign(player, { ready: player.isBot, x: spawn.x, y: spawn.y, angle: 0, alive: true, invulnerableUntil: 0, respawnAt: 0, kills: 0, deaths: 0, nextShotAt: 0, dashUntil: 0, nextDashAt: 0, currentQuestion: null, questionStats: emptyQuestionStats() }); } this.sendLobby(); this.broadcastEvent("Room reset. Real PC groups must mark ready for the next round."); }
  handleInput(playerId, message) { if (this.phase !== "playing") return; const player = this.players.get(playerId); if (!player || player.isBot || !player.connected || !player.alive || player.currentQuestion) return; const dx = clamp(Number(message.dx) || 0, -1, 1); const dy = clamp(Number(message.dy) || 0, -1, 1); const angle = Number.isFinite(Number(message.angle)) ? Number(message.angle) : player.angle; player.input = { dx, dy, angle, shoot: Boolean(message.shoot), dash: Boolean(message.dash) }; }
  handleAnswer(playerId, message) { if (this.phase !== "playing") return; const player = this.players.get(playerId); const question = player?.currentQuestion; if (!player || player.isBot || !question || question.id !== message.questionId) return; const now = Date.now(); const selectedIndex = Number(message.selectedIndex); const elapsedMs = clamp(now - question.createdAt, 0, QUESTION_DURATION_MS); const correct = selectedIndex === question.answerIndex && now <= question.expiresAt; this.recordAnswer(player, question, selectedIndex, correct ? "correct" : "wrong", elapsedMs); if (correct) { player.currentQuestion = null; player.respawnAt = now + 900; safeSend(player.ws, { type: "answer_result", correct: true, respawnInMs: 900 }); } else { safeSend(player.ws, { type: "answer_result", correct: false, correctIndex: question.answerIndex }); this.assignQuestion(player, 650); } }
  recordAnswer(player, question, selectedIndex, outcome, elapsedMs) { const stats = player.questionStats; stats.attempts += 1; if (outcome === "correct") stats.correct += 1; if (outcome === "wrong") stats.wrong += 1; if (outcome === "timeout") stats.timeouts += 1; stats.totalResponseMs += elapsedMs; stats.history.push({ questionId: question.id, type: question.type, prompt: question.prompt, options: question.options, selectedIndex, correctIndex: question.answerIndex, outcome, responseMs: elapsedMs, answeredAt: Date.now() }); }
  assignQuestion(player, delayMs = 0) { player.currentQuestion = null; setTimeout(() => { if (this.phase !== "playing" || player.isBot || player.alive || player.respawnAt) return; player.currentQuestion = createQuestion(); this.sendQuestion(player); }, delayMs); }
  sendQuestion(player) { const question = player.currentQuestion; if (question) safeSend(player.ws, { type: "question", id: question.id, questionType: question.type, prompt: question.prompt, options: question.options, diagram: question.diagram, expiresAt: question.expiresAt }); }
  eliminate(victim, killer) { if (!victim.alive || Date.now() < victim.invulnerableUntil) return; victim.alive = false; victim.deaths += 1; victim.respawnAt = victim.isBot ? Date.now() + 1500 : 0; victim.input = { dx: 0, dy: 0, angle: victim.angle, shoot: false, dash: false }; if (killer && killer.id !== victim.id) killer.kills += 1; this.broadcastEvent(`${victim.pcLabel} was eliminated${killer ? ` by ${killer.pcLabel}` : ""}.${victim.isBot ? " AI rebooting." : " Trigonometry is required to respawn."}`); if (!victim.isBot) this.assignQuestion(victim, 350); }
  respawn(player) { const teammates = [...this.players.values()].filter((candidate) => candidate.team === player.team && candidate.id !== player.id && candidate.alive); const spawn = teamSpawn(player.team, crypto.randomInt(3)); if (teammates.length) { const anchor = teammates[crypto.randomInt(teammates.length)]; spawn.x = clamp(anchor.x + crypto.randomInt(-90, 91), 40, ARENA.width - 40); spawn.y = clamp(anchor.y + crypto.randomInt(-90, 91), 40, ARENA.height - 40); } player.x = spawn.x; player.y = spawn.y; player.alive = true; player.respawnAt = 0; player.invulnerableUntil = Date.now() + 1800; this.paintTerritory(player.x, player.y, player.team, 1); safeSend(player.ws, { type: "respawned" }); }
  paintTerritory(x, y, team, radius = 1) { const cx = Math.floor(x / CELL_W); const cy = Math.floor(y / CELL_H); for (let gy = cy - radius; gy <= cy + radius; gy += 1) for (let gx = cx - radius; gx <= cx + radius; gx += 1) { if (gx < 0 || gx >= ARENA.gridWidth || gy < 0 || gy >= ARENA.gridHeight) continue; if ((gx - cx) ** 2 + (gy - cy) ** 2 > radius ** 2 + 0.6) continue; this.territory[gy * ARENA.gridWidth + gx] = team; } }
  territoryCounts() { const counts = [0, 0, 0]; for (const owner of this.territory) if (owner >= 0) counts[owner] += 1; return counts; }
  playerTerritoryCounts() { const counts = new Map([...this.players.keys()].map((playerId) => [playerId, 0])); const teamCounts = this.territoryCounts(); for (const team of [0, 1, 2]) { const members = [...this.players.values()].filter((player) => player.team === team); if (!members.length) continue; const share = Math.floor(teamCounts[team] / members.length); for (const player of members) counts.set(player.id, share); } return counts; }
  updateBots(now) { if (this.phase !== "playing") return; const enemiesByTeam = [0, 1, 2].map((team) => [...this.players.values()].filter((p) => p.team !== team && p.alive)); for (const bot of this.players.values()) { if (!bot.isBot || !bot.alive) continue; const enemies = enemiesByTeam[bot.team]; const target = enemies.sort((a, b) => Math.hypot(a.x - bot.x, a.y - bot.y) - Math.hypot(b.x - bot.x, b.y - bot.y))[0]; const goal = target || { x: ARENA.width / 2, y: ARENA.height / 2 }; const angle = Math.atan2(goal.y - bot.y, goal.x - bot.x); const strafe = Math.sin(now / 700 + bot.id.length) * 0.32; bot.input = { dx: Math.cos(angle) - Math.sin(angle) * strafe, dy: Math.sin(angle) + Math.cos(angle) * strafe, angle, shoot: Boolean(target && Math.hypot(target.x - bot.x, target.y - bot.y) < 650), dash: now >= bot.ai.nextDashAt }; if (bot.input.dash) bot.ai.nextDashAt = now + 2800 + crypto.randomInt(2200); } }
  tick() { const now = Date.now(); if (this.phase === "playing") { if (now >= this.endsAt) { this.endMatch(); return; } this.updateBots(now); this.updatePlayers(now); this.updateProjectiles(now); this.updateQuestionsAndRespawns(now); } if (now - this.lastStateAt >= 1000 / STATE_RATE) { this.lastStateAt = now; if (this.phase !== "lobby" || this.controller?.connected) this.broadcastState(now); } if (!this.controller?.connected && this.players.size === 0 && this.pending.size === 0 && now - this.updatedAt > ROOM_IDLE_TTL_MS) this.destroy(); }
  updatePlayers(now) { for (const player of this.players.values()) { if ((!player.isBot && !player.connected) || !player.alive || player.currentQuestion) continue; let { dx, dy } = player.input; const magnitude = Math.hypot(dx, dy); if (magnitude > 1) { dx /= magnitude; dy /= magnitude; } if (player.input.dash && now >= player.nextDashAt && magnitude > 0.05) { player.dashUntil = now + DASH_DURATION_MS; player.nextDashAt = now + DASH_COOLDOWN_MS; } const speed = now < player.dashUntil ? DASH_SPEED : PLAYER_SPEED; player.x = clamp(player.x + dx * speed * DT, PLAYER_RADIUS, ARENA.width - PLAYER_RADIUS); player.y = clamp(player.y + dy * speed * DT, PLAYER_RADIUS, ARENA.height - PLAYER_RADIUS); player.angle = player.input.angle; this.paintTerritory(player.x, player.y, player.team, now < player.dashUntil ? 2 : 1); if (player.input.shoot && now >= player.nextShotAt) { player.nextShotAt = now + SHOT_COOLDOWN_MS; const projectileId = id("shot"); this.projectiles.set(projectileId, { id: projectileId, ownerId: player.id, team: player.team, x: player.x + Math.cos(player.angle) * (PLAYER_RADIUS + 6), y: player.y + Math.sin(player.angle) * (PLAYER_RADIUS + 6), vx: Math.cos(player.angle) * PROJECTILE_SPEED, vy: Math.sin(player.angle) * PROJECTILE_SPEED, expiresAt: now + PROJECTILE_LIFETIME_MS }); } } }
  updateProjectiles(now) { for (const [projectileId, projectile] of this.projectiles) { projectile.x += projectile.vx * DT; projectile.y += projectile.vy * DT; if (now >= projectile.expiresAt || projectile.x < 0 || projectile.x > ARENA.width || projectile.y < 0 || projectile.y > ARENA.height) { this.projectiles.delete(projectileId); continue; } for (const target of this.players.values()) { if (!target.alive || target.team === projectile.team || now < target.invulnerableUntil) continue; if (Math.hypot(target.x - projectile.x, target.y - projectile.y) <= PLAYER_RADIUS + 7) { const killer = this.players.get(projectile.ownerId) || null; this.projectiles.delete(projectileId); this.eliminate(target, killer); break; } } } }
  updateQuestionsAndRespawns(now) { for (const player of this.players.values()) { if (!player.isBot && player.connected && player.currentQuestion && now > player.currentQuestion.expiresAt) { const timedOut = player.currentQuestion; this.recordAnswer(player, timedOut, null, "timeout", QUESTION_DURATION_MS); safeSend(player.ws, { type: "answer_result", correct: false, timeout: true, correctIndex: timedOut.answerIndex }); this.assignQuestion(player, 650); } if (!player.alive && player.respawnAt && now >= player.respawnAt) this.respawn(player); } }
  statePayload(now) { const territoryCounts = this.territoryCounts(); const playerTerritory = this.playerTerritoryCounts(); return { type: "state", roomCode: this.code, phase: this.phase, serverNow: now, remainingMs: this.phase === "playing" ? Math.max(0, this.endsAt - now) : MATCH_DURATION_MS, arena: ARENA, teamNames: this.teamNames, teamColors: this.teamColors, territory: Array.from(this.territory), territoryCounts, players: [...this.players.values()].map((player) => ({ id: player.id, name: player.pcLabel, pcLabel: player.pcLabel, students: player.students, team: player.team, isBot: player.isBot, connected: player.isBot || player.connected, ready: player.isBot || player.ready, x: Math.round(player.x * 10) / 10, y: Math.round(player.y * 10) / 10, angle: player.angle, alive: player.alive, invulnerable: now < player.invulnerableUntil, kills: player.kills, deaths: player.deaths, territory: playerTerritory.get(player.id) || 0, questions: player.questionStats.attempts, accuracy: player.questionStats.attempts ? player.questionStats.correct / player.questionStats.attempts : null, shotReadyAt: player.nextShotAt, dashReadyAt: player.nextDashAt })), projectiles: [...this.projectiles.values()].map((projectile) => ({ id: projectile.id, team: projectile.team, x: Math.round(projectile.x), y: Math.round(projectile.y) })) }; }
  broadcastState(now) { this.broadcast(this.statePayload(now)); }
  report() { const territoryCounts = this.territoryCounts(); const playerTerritory = this.playerTerritoryCounts(); return { roomCode: this.code, startedAt: this.startedAt, endedAt: Date.now(), matchDurationMs: this.startedAt ? Date.now() - this.startedAt : 0, configuredDurationMs: MATCH_DURATION_MS, winnerRule: "largest-territory", territoryCounts, teamNames: this.teamNames, teamColors: this.teamColors, teams: this.teamNames.map((name, team) => ({ name, color: this.teamColors[team], team, territory: territoryCounts[team] })), players: [...this.players.values()].map((player) => { const stats = player.questionStats; return { id: player.id, pcLabel: player.pcLabel, name: player.pcLabel, students: player.students, isBot: player.isBot, team: player.team, teamName: this.teamNames[player.team], teamColor: this.teamColors[player.team], territory: playerTerritory.get(player.id) || 0, kills: player.kills, deaths: player.deaths, attempts: stats.attempts, correct: stats.correct, wrong: stats.wrong, timeouts: stats.timeouts, accuracy: stats.attempts ? stats.correct / stats.attempts : null, averageResponseMs: stats.attempts ? Math.round(stats.totalResponseMs / stats.attempts) : null, answers: stats.history }; }) }; }
  finalPayload() { const report = this.report(); const maxTerritory = Math.max(...report.territoryCounts); const winners = report.teams.filter((team) => team.territory === maxTerritory).map((team) => team.team); return { type: "match_ended", winners, report }; }
  sendFinalTo(ws) { safeSend(ws, this.finalPayload()); }
  endMatch() { if (this.phase === "ended") return; this.phase = "ended"; this.broadcast(this.finalPayload()); this.sendLobby(); this.updatedAt = Date.now(); }
  disconnect(ws) { if (ws.role === "controller" && this.controller?.ws === ws) { this.controller.ws = null; this.controller.connected = false; this.controller.disconnectedAt = Date.now(); this.sendLobby(); this.broadcastEvent("Teacher controller disconnected. The room can be restored."); return; } if (ws.role === "pending" && ws.registrationId) { const pending = this.pending.get(ws.registrationId); if (!pending) return; pending.connected = false; pending.ws = null; setTimeout(() => { const current = this.pending.get(pending.id); if (current && !current.connected && this.phase === "lobby") { this.pending.delete(current.id); this.sendLobby(); } }, RECONNECT_GRACE_MS); this.sendLobby(); return; } if (ws.role === "player" && ws.playerId) { const player = this.players.get(ws.playerId); if (!player || player.isBot) return; player.connected = false; player.ws = null; player.disconnectedAt = Date.now(); player.ready = false; player.input = { dx: 0, dy: 0, angle: player.angle, shoot: false, dash: false }; this.sendLobby(); this.broadcastEvent(`${player.pcLabel} disconnected; reconnection is available for 60 seconds.`); } }
}

function roomFromMessage(message) { const code = String(message.roomCode || "").trim().toUpperCase(); const room = rooms.get(code); if (!room) throw new Error("Room not found. Check the six-character code."); return room; }
function handleMessage(ws, raw) { let message; try { message = JSON.parse(raw.toString()); } catch { safeSend(ws, { type: "error", message: "Invalid JSON message." }); return; } const now = Date.now(); ws.messageTimes = (ws.messageTimes || []).filter((time) => now - time < 1000); ws.messageTimes.push(now); if (ws.messageTimes.length > 90) { ws.close(1008, "Rate limit exceeded"); return; } try { switch (message.type) {
  case "create_control_room": { const code = makeRoomCode(); const room = new Room(code); rooms.set(code, room); room.attachController(ws); break; }
  case "restore_control": roomFromMessage(message).attachController(ws, String(message.masterToken || "")); break;
  case "register_student": roomFromMessage(message).registerStudent(ws, message); break;
  case "reconnect_student": roomFromMessage(message).reconnectStudent(ws, String(message.sessionToken || "")); break;
  case "approve_registration": rooms.get(ws.roomCode)?.approveRegistration(ws, message.registrationId, message.team); break;
  case "reject_registration": rooms.get(ws.roomCode)?.rejectRegistration(ws, message.registrationId); break;
  case "move_player": rooms.get(ws.roomCode)?.movePlayer(ws, message.playerId, message.team); break;
  case "remove_player": rooms.get(ws.roomCode)?.removePlayer(ws, message.playerId); break;
  case "set_registration_lock": rooms.get(ws.roomCode)?.setRegistrationLock(ws, message.locked); break;
  case "fill_with_bots": rooms.get(ws.roomCode)?.addBots(ws); break;
  case "remove_bots": rooms.get(ws.roomCode)?.removeBots(ws); break;
  case "submit_team_proposals": rooms.get(ws.roomCode)?.submitTeamProposals(ws.playerId, message.names); break;
  case "submit_team_votes": rooms.get(ws.roomCode)?.submitTeamVotes(ws.playerId, message.candidateKeys); break;
  case "set_ready": rooms.get(ws.roomCode)?.setReady(ws.playerId, message.ready); break;
  case "start_match": rooms.get(ws.roomCode)?.start(ws); break;
  case "end_match": rooms.get(ws.roomCode)?.endEarly(ws); break;
  case "reset_room": rooms.get(ws.roomCode)?.reset(ws); break;
  case "input": rooms.get(ws.roomCode)?.handleInput(ws.playerId, message); break;
  case "answer": rooms.get(ws.roomCode)?.handleAnswer(ws.playerId, message); break;
  case "ping": safeSend(ws, { type: "pong", clientTime: message.clientTime, serverTime: Date.now() }); break;
  default: throw new Error("Unsupported message type.");
} } catch (error) { safeSend(ws, { type: "error", message: error.message || "Request failed." }); } }

wss.on("connection", (ws) => { ws.isAlive = true; ws.role = "unassigned"; ws.on("pong", () => { ws.isAlive = true; }); ws.on("message", (raw) => handleMessage(ws, raw)); ws.on("close", () => rooms.get(ws.roomCode)?.disconnect(ws)); ws.on("error", () => {}); safeSend(ws, { type: "hello", protocol: PROTOCOL, serverTime: Date.now() }); });
const heartbeat = setInterval(() => { for (const ws of wss.clients) { if (!ws.isAlive) { ws.terminate(); continue; } ws.isAlive = false; ws.ping(); } }, 30_000);
server.listen(PORT, "0.0.0.0", () => console.log(`Triad Territory Rush protocol ${PROTOCOL} listening on port ${PORT}`));
function shutdown() { clearInterval(heartbeat); for (const room of rooms.values()) room.destroy(); server.close(() => process.exit(0)); setTimeout(() => process.exit(1), 5000).unref(); }
process.on("SIGTERM", shutdown); process.on("SIGINT", shutdown);
